# Generated by Django 5.0.6 on 2026-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=50)),
                ("rating", models.FloatField(default=0.0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.URLField(blank=True, null=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
